console:
  max_message_size_bytes: 409600
  username: "theousKaiAdmin1"
  password: "NCST_thesis"
logger:
  level: "DEBUG"
runtime:
  js_entrypoint: "build/index.js"
session:
  token_expiry_sec: 7200
socket:
  max_message_size_bytes: 4096
  max_request_size_bytes: 131072